# Generated by Django 2.2.7 on 2019-11-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='HR Photos/', verbose_name='Photo'),
        ),
    ]
