# Generated by Django 2.2.7 on 2019-11-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0002_hrprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='HR_Photos/', verbose_name='Photo'),
        ),
    ]
