# Generated by Django 2.2.7 on 2019-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0004_auto_20191123_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='HR_Photos/%b-%Y', verbose_name='Photo'),
        ),
    ]
