# Generated by Django 2.2.7 on 2019-12-04 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('contact_no', models.CharField(max_length=50, verbose_name='Contact No.')),
                ('alternate_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternate No.')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_cp', to='clients.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'ContactPerson',
                'verbose_name_plural': 'ContactPersons',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.FileField(upload_to='Agreements/%d-%m-%Y', verbose_name='Agreement Copy')),
                ('agreement_status', models.CharField(choices=[('signed', 'Signed'), ('unsigned', 'Unsigned')], max_length=50, verbose_name='Agreement Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('commission', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(39.99), django.core.validators.MaxValueValidator(100)], verbose_name='Commission Percentage')),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Salary')),
                ('max_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Salary')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='')),
                ('required_skills', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Required Skills')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
            },
        ),
    ]
