# Generated by Django 2.2.7 on 2019-12-07 06:46

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('clients', '0002_agreement_contactperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='required_skills',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='client_agreement'),
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Salary')),
                ('max_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Salary')),
                ('requirements', models.IntegerField(blank=True, null=True, verbose_name='Total Requirements')),
                ('min_experience', models.IntegerField(blank=True, null=True, verbose_name='Minimum Experience')),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Agreement', verbose_name='job_agreement')),
                ('required_skills', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Required Skills')),
            ],
        ),
    ]
