# Generated by Django 2.2.7 on 2019-12-07 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20191207_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='Agreements/%d-%m-%Y', verbose_name='Agreement Copy'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_agreement', to='clients.Client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_agreement', to='clients.Agreement', verbose_name='agreement'),
        ),
    ]
