# Generated by Django 2.2.7 on 2019-12-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20191207_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='for_client'),
        ),
    ]
