# Generated by Django 2.2.7 on 2019-12-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_jobdetail_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Job description'),
        ),
    ]
