# Generated by Django 2.2.7 on 2019-12-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_jobdetail_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Job Location'),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='designation',
            field=models.CharField(max_length=20, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='job_type',
            field=models.CharField(blank=True, choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship')], default=('fulltime', 'Full-Time'), max_length=50, null=True, verbose_name='Type'),
        ),
    ]
