# Generated by Django 2.2.7 on 2019-12-24 11:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20191224_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='required_skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Required Skills'),
        ),
    ]
