# Generated by Django 2.2.7 on 2019-12-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20191226_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='requirements',
            field=models.IntegerField(blank=True, null=True, verbose_name='Available Positions'),
        ),
    ]
