# Generated by Django 2.2.7 on 2020-01-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20191231_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Agreement Title'),
        ),
    ]
