# Generated by Django 2.2.7 on 2019-11-19 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=150, verbose_name='Remarks')),
                ('reviewed_on', models.DateField(default=django.utils.timezone.now, verbose_name='Reviewed on')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='candidates.Candidate', verbose_name='Candidates')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_profile.HRProfile', verbose_name='HR')),
            ],
            options={
                'verbose_name': 'HRRemark',
                'verbose_name_plural': 'HRRemarks',
            },
        ),
    ]
