# Generated by Django 2.2.7 on 2019-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_education_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Current CTC (in LPA)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected CTC (in LPA)'),
        ),
    ]
