# Generated by Django 2.2.7 on 2019-12-02 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20191130_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrremark',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='candidates.Candidate', verbose_name='Candidates'),
        ),
    ]
