# Generated by Django 2.2.7 on 2019-12-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrremark',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_profile.HRProfile', verbose_name='HR'),
        ),
    ]
