# Generated by Django 2.2.7 on 2019-12-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_auto_20191207_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrremark',
            name='remark',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Remarks'),
        ),
    ]
