# Generated by Django 2.2.7 on 2019-12-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_auto_20191207_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrremark',
            options={},
        ),
    ]
