# Generated by Django 2.2.7 on 2019-12-23 14:04

import candidates.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_auto_20191207_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=candidates.models.upload_photo_to),
        ),
    ]
