# Generated by Django 2.2.7 on 2019-12-26 11:51

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('candidates', '0011_candidate_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Title')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Your Role')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate', verbose_name='Candidates')),
                ('technologies', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Technologies Used')),
            ],
        ),
    ]
