# Generated by Django 2.2.7 on 2019-12-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20191226_1646'),
        ('candidates', '0014_auto_20191226_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrremark',
            name='considered_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Client', verbose_name='Considered for'),
        ),
        migrations.AddField(
            model_name='hrremark',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting-List'), ('shortlisted', 'Short-Listed'), ('rejected', 'Rejected'), ('not_interested', 'Not-Interested')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], verbose_name='till'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='hrremark',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hr_profile.HRProfile', verbose_name='HR'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='last_used',
            field=models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], null=True, verbose_name='Last Used'),
        ),
    ]
