# Generated by Django 2.2.7 on 2020-01-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_auto_20200106_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Designation'),
        ),
    ]
