# Generated by Django 2.2.7 on 2020-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_candidate_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Preferred Location'),
        ),
    ]
