# Generated by Django 2.2.7 on 2020-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_candidate_preferred_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='notice_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Notice Period (in days)'),
        ),
    ]
